security:
    encoders:
        Symfony\Component\Security\Core\User\User:
           algorithm: bcrypt
           cost:      10

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: $2a$10$hMcnR9ygE093BvaFIjy6B.w1QGD1Be3b0MJcWjE7z4OaNJFfbOO6S, roles: [ 'ROLE_USER' ] }
                    admin: { password: $2a$10$hMcnR9ygE093BvaFIjy6B.w1QGD1Be3b0MJcWjE7z4OaNJFfbOO6S, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:   ^/
            anonymous: ~
            form_login:
               login_path: login
               check_path: login_check

        login:
            pattern:  ^/login$
            security: false

        gitupdate:
            pattern:  ^/gitupdate$
            security: false

        #secured_area:
        #    pattern:    ^/demo/secured/
        #    form_login:
        #        check_path: _security_check
        #        login_path: _demo_login
        #    logout:
        #        path:   _demo_logout
        #        target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
