feature_branch_main_homepage:
    pattern:  /
    defaults: { _controller: FeatureBranchMainBundle:Default:index }
feature_branch_main_gitupdate:
    pattern:  /gitupdate
    defaults: { _controller: FeatureBranchMainBundle:Default:gitUpdate }
feature_branch_main_hosts_landing_page:
    pattern:  /hosts_landing_page
    defaults: { _controller: FeatureBranchMainBundle:Default:hostsLandingPage }
