parameters:
#    feature_branch_main.example.class: FeatureBranch\MainBundle\Example

services:
#    feature_branch_main.example:
#        class: %feature_branch_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
