parameters:
#    feature_branch_main.example.class: FeatureBranch\MainBundle\Example

services:
    feature_branch_ci_connector:
        class: FeatureBranch\MainBundle\CI\JenkinsConnector
        arguments: ['http://featurebranch.dev:8080']
        calls:
            - [setContainer, [@service_container]]

    feature_branch_ci:
        class: FeatureBranch\MainBundle\CI\CIJenkins
        arguments: ['app/data/branches_hosts.yaml', @feature_branch_ci_connector]

    feature_branch_gitclass:
        class: FeatureBranch\MainBundle\GitClass
        arguments: [@feature_branch_ci, '/tmp/repo_origin', '/tmp/repo_destination', '/tmp/repo_state.yaml']
