parameters:
#    feature_branch_main.example.class: FeatureBranch\MainBundle\Example

services:
    feature_branch_ci_connector:
        class: FeatureBranch\MainBundle\Service\CI\JenkinsConnector
        arguments: ['%feature_branch.ci_url%']
        calls:
            - [setContainer, [@service_container]]

    feature_branch_ci:
        class: FeatureBranch\MainBundle\Service\CI\CIJenkins
        arguments: ['%feature_branch.branches_hosts_config_file%', @feature_branch_ci_connector]

    feature_branch_gitclass:
        class: FeatureBranch\MainBundle\GitClass
        arguments: [@feature_branch_ci, '%feature_branch.repo_origin%', '%feature_branch.repo_destination%', '%feature_branch.repo_state_config_file%']
