parameters:
#    feature_branch_main.example.class: FeatureBranch\MainBundle\Example

services:
#    feature_branch_main.example:
#        class: %feature_branch_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    feature_branch_ci:
      class: FeatureBranch\MainBundle\CI\CILogger

    feature_branch_gitclass:
        class: FeatureBranch\MainBundle\GitClass
        arguments: [@feature_branch_ci]
